export const dummyProjects = [
  {
    _id: '1',
    project_name: 'GreenTech Solutions',
    description: 'Developing eco-friendly technology solutions to reduce carbon footprint.',
    field: 'Technology',
    budget: '$500,000',
    target: '$1,000,000',
    deadline: '2025-05-01',
    visibility: true,
    files: ['green-tech-overview.pdf', 'carbon-reduction-plan.pdf'],
  },
  {
    _id: '2',
    project_name: 'Smart Healthcare Initiative',
    description: 'Creating AI-based healthcare solutions for faster diagnosis and treatment.',
    field: 'Healthcare',
    budget: '$1,000,000',
    target: '$3,000,000',
    deadline: '2024-12-31',
    visibility: true,
    files: ['healthcare-tech-overview.pdf', 'ai-diagnosis-study.pdf'],
  },
  {
    _id: '3',
    project_name: 'Sustainable Agriculture Network',
    description: 'Building a platform for farmers to access sustainable farming practices and resources.',
    field: 'Agriculture',
    budget: '$200,000',
    target: '$500,000',
    deadline: '2025-07-01',
    visibility: true,
    files: ['sustainable-farming-guide.pdf', 'farmers-network.pdf'],
  },
  {
    _id: '4',
    project_name: 'Blockchain for Finance',
    description: 'Implementing blockchain technology to create secure and transparent financial systems.',
    field: 'Finance',
    budget: '$1,500,000',
    target: '$5,000,000',
    deadline: '2025-03-15',
    visibility: true,
    files: ['blockchain-finance.pdf', 'crypto-security-study.pdf'],
  },
  {
    _id: '5',
    project_name: 'AI-driven Education Platform',
    description: 'An AI-powered platform to personalize learning and enhance education worldwide.',
    field: 'Education',
    budget: '$300,000',
    target: '$750,000',
    deadline: '2025-06-01',
    visibility: false,
    files: ['ai-education-overview.pdf', 'personalized-learning.pdf'],
  },
  {
    _id: '6',
    project_name: 'Clean Water Access Program',
    description: 'Ensuring clean and accessible water for underserved communities globally.',
    field: 'Non-Profit',
    budget: '$1,000,000',
    target: '$2,500,000',
    deadline: '2025-04-20',
    visibility: true,
    files: ['water-access-report.pdf', 'clean-water-initiative.pdf'],
  },
  {
    _id: '7',
    project_name: 'Smart Cities Development',
    description: 'Building smart cities with integrated technology for better urban living.',
    field: 'Urban Development',
    budget: '$2,000,000',
    target: '$10,000,000',
    deadline: '2025-09-10',
    visibility: true,
    files: ['smart-cities-blueprint.pdf', 'urban-tech-study.pdf'],
  },
  {
    _id: '8',
    project_name: 'Solar Power Revolution',
    description: 'Investing in solar energy infrastructure to provide affordable clean energy worldwide.',
    field: 'Energy',
    budget: '$750,000',
    target: '$1,500,000',
    deadline: '2025-11-05',
    visibility: false,
    files: ['solar-power-report.pdf', 'clean-energy-strategy.pdf'],
  },
  {
    _id: '9',
    project_name: 'Space Exploration Fund',
    description: 'Funding private space missions to explore the universe and create opportunities for future generations.',
    field: 'Space Technology',
    budget: '$5,000,000',
    target: '$20,000,000',
    deadline: '2026-01-01',
    visibility: true,
    files: ['space-missions-overview.pdf', 'future-exploration-plan.pdf'],
  },
]
